[package]
name = "blackflower-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
profile-with-tracy = ["blackflower-observability/profile-with-tracy"]

[dependencies]
blackflower-acoustics.workspace = true
blackflower-networking.workspace = true
blackflower-networking-quic.workspace = true
blackflower-networking-replication.workspace = true
blackflower-observability.workspace = true
blackflower-world-simulation.workspace = true

anyhow.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
blackflower-audio-capture.workspace = true
blackflower-audio-voice.workspace = true
rcgen.workspace = true
rustls.workspace = true

[lints]
workspace = true
