[package]
name = "blackflower"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
profile-with-tracy = ["blackflower-observability/profile-with-tracy"]

[dependencies]
anyhow.workspace = true
blackflower-observability.workspace = true
blackflower-prediction = { workspace = true, features = ["observability"] }
blackflower-presentation = { workspace = true, features = ["observability"] }

[lints]
workspace = true
