[package]
name = "blackflower"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
profile-with-tracy = ["blackflower-observability/profile-with-tracy"]

[dependencies]
blackflower-assets = { workspace = true, features = ["signing", "unversioned-loading"] }
blackflower-ecs.workspace = true
blackflower-harness.workspace = true
blackflower-networking.workspace = true
blackflower-networking-protocol.workspace = true
blackflower-networking-quic.workspace = true
blackflower-networking-replication.workspace = true
blackflower-observability.workspace = true
blackflower-observability-tui.workspace = true
blackflower-rendering.workspace = true
blackflower-world-prediction = { workspace = true, features = ["observability"] }
blackflower-world-presentation = { workspace = true, features = ["observability"] }

anyhow.workspace = true
bytemuck.workspace = true
bytes.workspace = true
clap.workspace = true
glam.workspace = true
image.workspace = true
ratatui.workspace = true
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
winit.workspace = true

[lints]
workspace = true
