[package]
name = "blackflower-shader-compiler"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
links = "slang"

[dependencies]
bytes.workspace = true
thiserror.workspace = true

[build-dependencies]
bindgen.workspace = true
cmake.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
