[package]
name = "blackflower-harness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
observability = ["blackflower-world-prediction/observability"]

[dependencies]
blackflower-ecs.workspace = true
blackflower-networking.workspace = true
blackflower-networking-protocol.workspace = true
blackflower-networking-quic.workspace = true
blackflower-networking-replication.workspace = true
blackflower-world-prediction.workspace = true

bytemuck.workspace = true
bytes.workspace = true
glam.workspace = true
thiserror.workspace = true

[lints]
workspace = true
