[package]
name = "blackflower-networking-quic"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blackflower-networking.workspace = true

bytes.workspace = true
quinn.workspace = true
rustls.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
rcgen.workspace = true

[lints]
workspace = true
