#ifndef BLACKFLOWER_FLECS_CONFIG_H
#define BLACKFLOWER_FLECS_CONFIG_H

#define FLECS_CUSTOM_BUILD
#define FLECS_SYSTEM
#define FLECS_PIPELINE
#define FLECS_QUERY_DSL

#ifdef BLACKFLOWER_ECS_ENABLE_STATS
#define FLECS_STATS
#endif

#endif
