[package]
name = "blackflower-rendering-textures"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
bytes.workspace = true
thiserror.workspace = true

[build-dependencies]
bindgen.workspace = true
cmake.workspace = true

[lints]
workspace = true
