[package]
name = "blackflower-audio-spatial"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
links = "phonon"

[features]
default = []
# Trusted offline cooker access to freshly serialized Steam Audio scenes.
cooking = []

[dependencies]
blackflower-acoustics.workspace = true
blackflower-assets.workspace = true

blake3.workspace = true
glam.workspace = true
thiserror.workspace = true

[build-dependencies]
blackflower-build.workspace = true

bindgen.workspace = true

[lints]
workspace = true
