[package]
name = "blackflower-audio-spatial"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
links = "phonon"

[dependencies]
glam.workspace = true
thiserror.workspace = true

[build-dependencies]
bindgen.workspace = true
cmake.workspace = true

[lints]
workspace = true
