[package]
name = "blackflower-world-presentation"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
metrics = ["blackflower-ecs/metrics", "dep:metrics"]
profiling = ["blackflower-ecs/profiling", "dep:profiling"]
tracing = ["blackflower-ecs/tracing", "dep:tracing"]
observability = ["metrics", "profiling", "tracing"]

[dependencies]
blackflower-acoustics.workspace = true
blackflower-ecs.workspace = true
blackflower-rendering.workspace = true
glam.workspace = true

metrics = { workspace = true, optional = true }
profiling = { workspace = true, optional = true }
strum.workspace = true
thiserror.workspace = true
tracing = { workspace = true, optional = true }

[dev-dependencies]
bytemuck.workspace = true

[lints]
workspace = true
