use std::path::Path;
use wasmtime::component::{Component, Linker, ResourceTable};
use wasmtime::{Config, Engine, Store};
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiCtxView, WasiView};

wasmtime::component::bindgen!({
    path: "../../wit/game-plugin.wit",
    world: "game-plugin",
});

/// Raw prop list as used by the WASM interface — `(id, raw bytes)`.
pub type PropList = Vec<(u16, Vec<u8>)>;

struct PluginState {
    ctx: WasiCtx,
    table: ResourceTable,
}

impl WasiView for PluginState {
    fn ctx(&mut self) -> WasiCtxView<'_> {
        WasiCtxView {
            ctx: &mut self.ctx,
            table: &mut self.table,
        }
    }
}

/// Host-side WASM plugin. Loads a component and exposes engine hooks.
/// `GamePlugin` is generated by `bindgen!`; this struct owns the store.
pub struct Plugin {
    store: Store<PluginState>,
    bindings: GamePlugin,
}

impl Plugin {
    pub fn load(path: &Path) -> anyhow::Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true);
        let engine =
            Engine::new(&config).map_err(|e| anyhow::anyhow!("creating wasmtime engine: {e}"))?;

        let component = Component::from_file(&engine, path)
            .map_err(|e| anyhow::anyhow!("loading plugin from {}: {e}", path.display()))?;

        let mut linker: Linker<PluginState> = Linker::new(&engine);
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| anyhow::anyhow!("adding WASI to plugin linker: {e}"))?;

        let state = PluginState {
            ctx: WasiCtxBuilder::new().build(),
            table: ResourceTable::new(),
        };
        let mut store = Store::new(&engine, state);

        let bindings = GamePlugin::instantiate(&mut store, &component, &linker)
            .map_err(|e| anyhow::anyhow!("instantiating plugin component: {e}"))?;

        Ok(Self { store, bindings })
    }

    /// Pick which map spawn point a player spawns at. `candidates` are
    /// `(origin, angle)` pairs from the map; returns the chosen index,
    /// clamped into range against `candidates.len()`.
    pub fn select_spawn(&mut self, candidates: &[([f32; 3], f32)]) -> anyhow::Result<usize> {
        if candidates.is_empty() {
            return Ok(0);
        }
        let wit: Vec<SpawnPoint> = candidates
            .iter()
            .map(|&(origin, angle)| SpawnPoint {
                origin: Vec3 {
                    x: origin[0],
                    y: origin[1],
                    z: origin[2],
                },
                angle,
            })
            .collect();
        let idx = self
            .bindings
            .call_select_spawn(&mut self.store, &wit)
            .map_err(|e| anyhow::anyhow!("plugin select_spawn: {e}"))?;
        Ok((idx as usize) % candidates.len())
    }

    /// Called when a new player entity is spawned.
    pub fn on_spawn(&mut self) -> anyhow::Result<PropList> {
        self.bindings
            .call_on_spawn(&mut self.store)
            .map_err(|e| anyhow::anyhow!("plugin on_spawn: {e}"))
    }

    /// Called when a hitscan ray confirms a hit on the target.
    pub fn on_hit(&mut self, target_props: &PropList) -> anyhow::Result<PropList> {
        self.bindings
            .call_on_hit(&mut self.store, target_props)
            .map_err(|e| anyhow::anyhow!("plugin on_hit: {e}"))
    }
}
