[package]
name = "blackflower-harness"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
profile-with-tracy = ["blackflower-observability/profile-with-tracy"]

[dependencies]
blackflower-observability.workspace = true
blackflower-world-prediction = { workspace = true, features = ["observability"] }

anyhow.workspace = true
metrics.workspace = true

[dev-dependencies]
tracing.workspace = true

[lints]
workspace = true
