[package]
name = "blackflower-cooker-acoustics"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blackflower-acoustics.workspace = true
blackflower-audio-media.workspace = true
blackflower-audio-spatial = { workspace = true, features = ["cooking"] }
blackflower-gltf-metadata.workspace = true

blake3.workspace = true
glam.workspace = true
gltf.workspace = true
bytes.workspace = true
thiserror.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
