use std::cmp::Reverse;
use std::collections::BTreeMap;

use blackflower_spatial_query::{
    Device as SpatialQueryDevice, GeometryId, Scene as SpatialQueryScene,
    SurfaceHit as SpatialQueryHit, Triangle as SpatialQueryTriangle, Vec3A,
};

use crate::{
    ACOUSTIC_SAMPLE_RATE, AcousticDynamicState, AcousticEmissionProfile, AcousticMaterialLibrary,
    AcousticObservation, AcousticPrefab, AcousticReceiver, AcousticSimulationScene,
    AcousticStructureVersion, AcousticTopology, AudibleSoundDelivery, AudibleVoiceDelivery,
    BandEnergy, Error, PositionMm, PropagationDescriptor, QuantizedTriangle, SAMPLES_PER_TICK,
    SOUND_SPEED_MM_PER_SECOND, SoundEmission,
};

const MAX_PORTAL_ROUTE_EXPANSIONS: usize = 1_000_000;

/// Fixed-capacity release profile for one authoritative acoustic world.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AcousticWorldSettings {
    /// Maximum receivers active in a tick.
    pub max_receivers: usize,
    /// Maximum newly captured emissions in a tick.
    pub max_active_emissions: usize,
    /// Maximum candidate source/receiver pairs resolved in a tick.
    pub max_candidate_pairs: usize,
    /// Maximum alternate zone paths retained per pair.
    pub max_paths_per_pair: usize,
    /// Maximum crossed surfaces resolved for transmission.
    pub max_transmission_surfaces: usize,
    /// Maximum simultaneously retained live voice frames for one client.
    pub max_client_voices: usize,
    /// Maximum retained transient observations across the AI interval.
    pub max_recent_observations: usize,
}

impl Default for AcousticWorldSettings {
    fn default() -> Self {
        Self {
            max_receivers: 96,
            max_active_emissions: 512,
            max_candidate_pairs: 4_096,
            max_paths_per_pair: 4,
            max_transmission_surfaces: 8,
            max_client_voices: 128,
            max_recent_observations: 16_384,
        }
    }
}

/// Complete facts and gated deliveries generated by one acoustic tick.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AcousticFrame {
    /// Structure revision used for every solve in this frame.
    pub structure_version: AcousticStructureVersion,
    /// New bot observations created by emissions captured this tick.
    pub observations: Vec<AcousticObservation>,
    /// Gated non-voice deliveries.
    pub sounds: Vec<AudibleSoundDelivery>,
    /// Gated exact-Opus voice deliveries.
    pub voices: Vec<AudibleVoiceDelivery>,
    /// Number of direct/transmission pairs preserved regardless of indirect budget.
    pub direct_pairs: usize,
    /// Number of source/receiver pairs receiving indirect path refinement.
    pub candidate_pairs: usize,
    /// Number of pairs omitted when the deterministic pair budget was exhausted.
    pub deferred_indirect_pairs: usize,
}

/// Replay-safe source envelope without PCM, Opus, position, or entity identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct AcousticReplayEmission {
    /// Physical sound class.
    pub class: crate::SoundClass,
    /// Source sample on the authoritative timeline.
    pub start_sample: u64,
    /// Authored/calibrated source level.
    pub reference_spl_db_q8: i32,
    /// Quantized source envelope for this tick.
    pub bands: BandEnergy,
}

/// Replay-safe delivery fact; voice contains no stream, sequence, payload, or identity.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum AcousticReplayDelivery {
    /// Non-voice client event delivery.
    Sound {
        /// Recipient ID owned by replay routing.
        receiver_id: u32,
        /// Public client event ID.
        client_event_id: u32,
        /// Authoritative path parameters.
        propagation: PropagationDescriptor,
    },
    /// Physical voice audibility fact without conversation data.
    Voice {
        /// Recipient ID owned by replay routing.
        receiver_id: u32,
        /// Authoritative path parameters.
        propagation: PropagationDescriptor,
    },
}

/// Facts retained for deterministic replay without recorded conversation.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct AcousticReplayFacts {
    /// Structure revision used by all facts.
    pub structure_version: AcousticStructureVersion,
    /// Source envelopes captured this tick.
    pub emissions: Vec<AcousticReplayEmission>,
    /// Privacy-preserving bot observations.
    pub observations: Vec<AcousticObservation>,
    /// Gated delivery facts with voice payloads deliberately erased.
    pub deliveries: Vec<AcousticReplayDelivery>,
}

impl AcousticReplayFacts {
    fn with_capacity(settings: AcousticWorldSettings, max_direct_pairs: usize) -> Self {
        Self {
            structure_version: AcousticStructureVersion(1),
            emissions: Vec::with_capacity(settings.max_active_emissions),
            observations: Vec::with_capacity(max_direct_pairs),
            deliveries: Vec::with_capacity(max_direct_pairs),
        }
    }

    fn clear(&mut self, version: AcousticStructureVersion) {
        self.structure_version = version;
        self.emissions.clear();
        self.observations.clear();
        self.deliveries.clear();
    }
}

impl AcousticFrame {
    fn with_capacity(settings: AcousticWorldSettings, max_direct_pairs: usize) -> Self {
        Self {
            structure_version: AcousticStructureVersion(1),
            observations: Vec::with_capacity(max_direct_pairs),
            sounds: Vec::with_capacity(max_direct_pairs),
            voices: Vec::with_capacity(settings.max_candidate_pairs),
            direct_pairs: 0,
            candidate_pairs: 0,
            deferred_indirect_pairs: 0,
        }
    }

    fn clear(&mut self, version: AcousticStructureVersion) {
        self.structure_version = version;
        self.observations.clear();
        self.sounds.clear();
        self.voices.clear();
        self.direct_pairs = 0;
        self.candidate_pairs = 0;
        self.deferred_indirect_pairs = 0;
    }
}

#[derive(Debug)]
struct ActiveGeometry {
    scene: SpatialQueryScene,
    geometry_id: Option<GeometryId>,
    material_indices: Vec<u16>,
}

#[derive(Debug, Clone, Copy)]
struct ResolvedPath {
    length_mm: u64,
    gain: BandEnergy,
    direction_target: PositionMm,
    direct: bool,
    uncertainty_q16: u16,
}

#[derive(Debug, Clone, Copy)]
struct ResolvedPair {
    emission_index: usize,
    receiver: AcousticReceiver,
    path: ResolvedPath,
}

#[derive(Debug, Clone, Copy)]
struct PropagatedPair {
    emission_index: usize,
    receiver: AcousticReceiver,
    descriptor: PropagationDescriptor,
}

#[derive(Debug, Clone, Copy)]
struct ReceiverGroup {
    zone: Option<u32>,
    begin: usize,
    end: usize,
}

/// Authoritative solver with shared spatial queries and fixed-capacity arrival/observation state.
#[derive(Debug)]
pub struct AcousticWorld {
    settings: AcousticWorldSettings,
    materials: AcousticMaterialLibrary,
    topology: AcousticTopology,
    scene: AcousticSimulationScene,
    prefabs: BTreeMap<String, AcousticPrefab>,
    version: AcousticStructureVersion,
    active_states: BTreeMap<u32, AcousticDynamicState>,
    staged_states: BTreeMap<u32, AcousticDynamicState>,
    spatial_device: SpatialQueryDevice,
    active_geometry: ActiveGeometry,
    portal_routes: BTreeMap<(u32, u32), Vec<CachedPortalRoute>>,
    receivers: Vec<AcousticReceiver>,
    receiver_groups: Vec<ReceiverGroup>,
    client_voice_counts: Vec<(u32, usize)>,
    emissions: Vec<SoundEmission>,
    frame: AcousticFrame,
    replay_facts: AcousticReplayFacts,
    resolved_pairs: Vec<ResolvedPair>,
    propagated_pairs: Vec<PropagatedPair>,
    recent_observations: Vec<AcousticObservation>,
    surface_hits: Vec<SpatialQueryHit>,
}

impl AcousticWorld {
    /// Validate dependencies, allocate all tick pools, and activate topology defaults.
    #[allow(
        clippy::too_many_lines,
        reason = "world construction validates every asset boundary before publishing one coherent solver"
    )]
    pub fn new(
        materials: AcousticMaterialLibrary,
        topology: AcousticTopology,
        scene: AcousticSimulationScene,
        prefabs: Vec<AcousticPrefab>,
        settings: AcousticWorldSettings,
    ) -> Result<Self, Error> {
        validate_settings(settings)?;
        let max_direct_pairs = settings
            .max_receivers
            .checked_mul(settings.max_active_emissions)
            .ok_or(Error::ResourceLimit("direct acoustic pairs"))?;
        validate_material_indices(&scene.triangles, materials.materials().len())?;
        let mut prefab_map = BTreeMap::new();
        for prefab in prefabs {
            for state in prefab.states() {
                validate_material_indices(&state.triangles, materials.materials().len())?;
            }
            if prefab_map.insert(prefab.name.clone(), prefab).is_some() {
                return Err(Error::DuplicateIdentifier("prefab".to_owned()));
            }
        }
        let mut active_states = BTreeMap::new();
        for instance in topology.instances() {
            let prefab = prefab_map
                .get(&instance.prefab)
                .ok_or_else(|| Error::MissingReference(instance.prefab.clone()))?;
            if prefab.state(instance.default_state).is_none() {
                return Err(Error::MissingReference(format!(
                    "{} state {}",
                    instance.prefab, instance.default_state
                )));
            }
            active_states.insert(
                instance.id,
                AcousticDynamicState {
                    instance_id: instance.id,
                    state_id: Some(instance.default_state),
                    transform: crate::QuantizedTransform::translated(PositionMm::default()),
                    portal_open_q16: None,
                },
            );
        }
        let spatial_device = SpatialQueryDevice::new()?;
        let active_geometry = build_active_geometry(
            &spatial_device,
            &scene,
            &topology,
            &prefab_map,
            &active_states,
        )?;
        let portal_routes = build_portal_routes(&topology, &scene, settings.max_paths_per_pair)?;
        let receiver_group_capacity = topology.zones().len().saturating_add(1);
        Ok(Self {
            settings,
            materials,
            topology,
            scene,
            prefabs: prefab_map,
            version: AcousticStructureVersion(1),
            active_states,
            staged_states: BTreeMap::new(),
            spatial_device,
            active_geometry,
            portal_routes,
            receivers: Vec::with_capacity(settings.max_receivers),
            receiver_groups: Vec::with_capacity(receiver_group_capacity),
            client_voice_counts: Vec::with_capacity(settings.max_receivers),
            emissions: Vec::with_capacity(settings.max_active_emissions),
            frame: AcousticFrame::with_capacity(settings, max_direct_pairs),
            replay_facts: AcousticReplayFacts::with_capacity(settings, max_direct_pairs),
            resolved_pairs: Vec::with_capacity(max_direct_pairs),
            propagated_pairs: Vec::with_capacity(max_direct_pairs),
            recent_observations: Vec::with_capacity(settings.max_recent_observations),
            surface_hits: Vec::with_capacity(settings.max_transmission_surfaces),
        })
    }

    /// Active structural revision.
    #[must_use]
    pub const fn structure_version(&self) -> AcousticStructureVersion {
        self.version
    }

    /// Replace the canonical receiver set for the next solve.
    pub fn set_receivers(&mut self, receivers: &[AcousticReceiver]) -> Result<(), Error> {
        if receivers.len() > self.settings.max_receivers {
            return Err(Error::ResourceLimit("receivers"));
        }
        self.receivers.clear();
        self.receivers.extend_from_slice(receivers);
        self.receivers.sort_by_key(|receiver| receiver.id);
        if self
            .receivers
            .windows(2)
            .any(|pair| pair[0].id == pair[1].id)
        {
            return Err(Error::DuplicateIdentifier("receiver".to_owned()));
        }
        for receiver in &mut self.receivers {
            receiver.zone = resolve_zone(&self.topology, receiver.zone, receiver.position);
        }
        self.receivers
            .sort_by_key(|receiver| (receiver.zone, receiver.id));
        self.receiver_groups.clear();
        self.client_voice_counts.clear();
        for index in 0..self.receivers.len() {
            let zone = self.receivers[index].zone;
            if self
                .receiver_groups
                .last()
                .is_some_and(|group| group.zone == zone)
            {
                if let Some(group) = self.receiver_groups.last_mut() {
                    group.end = index + 1;
                }
            } else {
                self.receiver_groups.push(ReceiverGroup {
                    zone,
                    begin: index,
                    end: index + 1,
                });
            }
        }
        self.client_voice_counts.extend(
            self.receivers
                .iter()
                .filter(|receiver| !receiver.bot)
                .map(|receiver| (receiver.id, 0)),
        );
        Ok(())
    }

    /// Queue one action, phenomenon, or voice emission for the active tick.
    pub fn capture_emission(&mut self, emission: SoundEmission) -> Result<(), Error> {
        if self.emissions.len() >= self.settings.max_active_emissions {
            return Err(Error::ResourceLimit("active emissions"));
        }
        if emission.voice.is_some() && emission.class != crate::SoundClass::Voice {
            return Err(Error::InvalidField("voice sound class"));
        }
        self.emissions.push(emission);
        Ok(())
    }

    /// Build one emission from a cooked `.bfacprf` envelope frame.
    #[must_use]
    pub fn emission_from_profile(
        id: u64,
        position: PositionMm,
        zone: Option<u32>,
        start_sample: u64,
        profile: &AcousticEmissionProfile,
        frame: usize,
        priority: u8,
    ) -> Option<SoundEmission> {
        let envelope = profile.frames.get(frame)?;
        Some(SoundEmission {
            id,
            client_event_id: profile.client_event_id,
            position,
            zone,
            start_sample,
            reference_spl_db_q8: profile.reference_spl_db_q8,
            bands: envelope
                .bands
                .multiplied(BandEnergy([envelope.amplitude_q16; 3])),
            directivity_q16: profile.directivity_q16,
            forward_q15: [0, 0, i16::MAX],
            class: profile.class,
            priority,
            voice: None,
        })
    }

    /// Stage a committed door, destructible, or portal state for publication after this tick.
    pub fn stage_dynamic_state(&mut self, state: AcousticDynamicState) -> Result<(), Error> {
        if !self
            .topology
            .instances()
            .iter()
            .any(|instance| instance.id == state.instance_id)
        {
            return Err(Error::MissingReference(format!(
                "instance {}",
                state.instance_id
            )));
        }
        self.staged_states.insert(state.instance_id, state);
        Ok(())
    }

    /// Resolve the active tick and publish staged structural changes for the next tick.
    pub fn step(&mut self, tick: u64) -> Result<&AcousticFrame, Error> {
        self.capture_tick(tick);
        self.resolve_acoustic_paths()?;
        self.advance_acoustic_propagation();
        self.build_acoustic_observations()?;
        self.capture_acoustic_facts(tick);
        self.update_acoustic_structure()?;
        Ok(&self.frame)
    }

    /// Canonicalize captured inputs and open one staged acoustic solve.
    pub fn capture_tick(&mut self, _tick: u64) {
        self.frame.clear(self.version);
        self.resolved_pairs.clear();
        self.propagated_pairs.clear();
        for (_receiver, count) in &mut self.client_voice_counts {
            *count = 0;
        }
        self.emissions.sort_by_key(|emission| {
            (
                emission.start_sample,
                Reverse(emission.reference_spl_db_q8),
                Reverse(emission.priority),
                emission.id,
            )
        });
    }

    /// Resolve direct/transmission and stable alternate paths for bounded candidates.
    pub fn resolve_acoustic_paths(&mut self) -> Result<(), Error> {
        for emission_index in 0..self.emissions.len() {
            let emission = self.emissions[emission_index].clone();
            let source_zone = self.resolve_zone(emission.zone, emission.position);
            for group_index in 0..self.receiver_groups.len() {
                let group = self.receiver_groups[group_index];
                if !self.zones_may_connect(source_zone, group.zone) {
                    continue;
                }
                for receiver_index in group.begin..group.end {
                    let receiver = self.receivers[receiver_index];
                    self.frame.direct_pairs = self.frame.direct_pairs.saturating_add(1);
                    let indirect_available = source_zone.zip(group.zone).is_some_and(|zones| {
                        zones.0 != zones.1 && self.portal_routes.contains_key(&zones)
                    });
                    let allow_indirect = indirect_available
                        && self.frame.candidate_pairs < self.settings.max_candidate_pairs;
                    if allow_indirect {
                        self.frame.candidate_pairs += 1;
                    } else if indirect_available {
                        self.frame.deferred_indirect_pairs =
                            self.frame.deferred_indirect_pairs.saturating_add(1);
                    }
                    let path = self.resolve_path(&emission, receiver, allow_indirect)?;
                    if self.resolved_pairs.len() < self.resolved_pairs.capacity() {
                        self.resolved_pairs.push(ResolvedPair {
                            emission_index,
                            receiver,
                            path,
                        });
                    }
                }
            }
        }
        Ok(())
    }

    /// Apply source strength, distance, materials, directivity, and speed-of-sound delay.
    pub fn advance_acoustic_propagation(&mut self) {
        for pair in &self.resolved_pairs {
            let Some(emission) = self.emissions.get(pair.emission_index) else {
                continue;
            };
            if self.propagated_pairs.len() < self.propagated_pairs.capacity() {
                self.propagated_pairs.push(PropagatedPair {
                    emission_index: pair.emission_index,
                    receiver: pair.receiver,
                    descriptor: descriptor(
                        self.version,
                        &self.scene,
                        emission,
                        pair.receiver,
                        pair.path,
                    ),
                });
            }
        }
    }

    /// Apply masking/hearing gates and build privacy-preserving observations or deliveries.
    pub fn build_acoustic_observations(&mut self) -> Result<(), Error> {
        for index in 0..self.propagated_pairs.len() {
            let pair = self.propagated_pairs[index];
            let Some(emission) = self.emissions.get(pair.emission_index).cloned() else {
                continue;
            };
            self.emit_propagated(&emission, pair.receiver, pair.descriptor)?;
        }
        Ok(())
    }

    /// Canonically order facts, retain transients for AI, and close captured inputs.
    pub fn capture_acoustic_facts(&mut self, tick: u64) {
        canonicalize_frame(&mut self.frame);
        self.replay_facts.clear(self.frame.structure_version);
        self.replay_facts
            .emissions
            .extend(
                self.emissions
                    .iter()
                    .map(|emission| AcousticReplayEmission {
                        class: emission.class,
                        start_sample: emission.start_sample,
                        reference_spl_db_q8: emission.reference_spl_db_q8,
                        bands: emission.bands,
                    }),
            );
        self.replay_facts
            .observations
            .extend_from_slice(&self.frame.observations);
        self.replay_facts
            .deliveries
            .extend(
                self.frame
                    .sounds
                    .iter()
                    .map(|delivery| AcousticReplayDelivery::Sound {
                        receiver_id: delivery.receiver_id,
                        client_event_id: delivery.client_event_id,
                        propagation: delivery.propagation,
                    }),
            );
        self.replay_facts
            .deliveries
            .extend(
                self.frame
                    .voices
                    .iter()
                    .map(|delivery| AcousticReplayDelivery::Voice {
                        receiver_id: delivery.receiver_id,
                        propagation: delivery.propagation,
                    }),
            );
        self.retain_recent(tick.saturating_mul(SAMPLES_PER_TICK));
        self.emissions.clear();
    }

    /// Publish committed dynamic changes after the solve so the new revision starts next tick.
    pub fn update_acoustic_structure(&mut self) -> Result<(), Error> {
        self.publish_staged_structure()
    }

    /// Observations retained across the 48 ticks between 5 Hz bot perception updates.
    #[must_use]
    pub fn recent_observations(&self) -> &[AcousticObservation] {
        &self.recent_observations
    }

    /// Latest completed frame, including authoritative deliveries and facts.
    #[must_use]
    pub const fn frame(&self) -> &AcousticFrame {
        &self.frame
    }

    /// Latest replay-safe facts; voice payloads and source identities are absent by type.
    #[must_use]
    pub const fn replay_facts(&self) -> &AcousticReplayFacts {
        &self.replay_facts
    }

    #[allow(
        clippy::too_many_lines,
        reason = "one authoritative gate produces mutually exclusive bot, sound, and voice outputs"
    )]
    fn emit_propagated(
        &mut self,
        emission: &SoundEmission,
        receiver: AcousticReceiver,
        descriptor: PropagationDescriptor,
    ) -> Result<(), Error> {
        let received_db_q8 = emission
            .reference_spl_db_q8
            .saturating_add(descriptor.gain_db_q8);
        let threshold = receiver.threshold_db_q8.max(receiver.masking_db_q8);
        if received_db_q8 < threshold || descriptor.band_gain.peak() == 0 {
            return Ok(());
        }
        if receiver.bot {
            let energy = emission
                .bands
                .multiplied(descriptor.band_gain)
                .multiplied(receiver.hearing);
            if energy.peak() == 0
                || self.frame.observations.len() >= self.frame.observations.capacity()
            {
                return Ok(());
            }
            self.frame.observations.push(AcousticObservation {
                receiver_id: receiver.id,
                observation_token: observation_token(
                    receiver.id,
                    emission.id,
                    descriptor.arrival_sample,
                ),
                class: emission.class,
                arrival_sample: descriptor.arrival_sample,
                energy,
                direction_q15: descriptor.direction_q15,
                uncertainty_q16: descriptor.uncertainty_q16,
            });
        } else if let Some(encoded) = &emission.voice {
            let count = self
                .client_voice_counts
                .iter_mut()
                .find(|(receiver_id, _count)| *receiver_id == receiver.id)
                .map(|(_receiver_id, count)| count);
            if count
                .as_ref()
                .is_some_and(|count| **count < self.settings.max_client_voices)
                && self.frame.voices.len() < self.frame.voices.capacity()
            {
                self.frame.voices.push(AudibleVoiceDelivery {
                    receiver_id: receiver.id,
                    play_sample: descriptor.arrival_sample,
                    propagation: descriptor,
                    encoded: encoded.clone(),
                });
                if let Some(count) = count {
                    *count += 1;
                }
            }
        } else if self.frame.sounds.len() < self.frame.sounds.capacity() {
            self.frame.sounds.push(AudibleSoundDelivery {
                receiver_id: receiver.id,
                client_event_id: emission.client_event_id,
                play_sample: descriptor.arrival_sample,
                propagation: descriptor,
            });
        }
        Ok(())
    }

    fn resolve_path(
        &mut self,
        emission: &SoundEmission,
        receiver: AcousticReceiver,
        allow_indirect: bool,
    ) -> Result<ResolvedPath, Error> {
        self.active_geometry.scene.intersect_segment(
            spatial_position(emission.position),
            spatial_position(receiver.position),
            self.settings.max_transmission_surfaces,
            &mut self.surface_hits,
        )?;
        let mut gain = BandEnergy::UNITY;
        for hit in &self.surface_hits {
            if Some(hit.geometry_id()) != self.active_geometry.geometry_id {
                return Err(Error::InvalidField("spatial-query geometry ID"));
            }
            let material_index = usize::try_from(hit.primitive_id().0)
                .ok()
                .and_then(|index| self.active_geometry.material_indices.get(index))
                .copied()
                .ok_or(Error::InvalidField("spatial-query primitive ID"))?;
            if let Some(material) = self.materials.materials().get(usize::from(material_index)) {
                gain = gain.multiplied(material.transmission);
            }
        }
        let direct = ResolvedPath {
            length_mm: emission.position.distance(receiver.position),
            gain,
            direction_target: emission.position,
            direct: true,
            uncertainty_q16: if self.surface_hits.is_empty() {
                512
            } else {
                8_192
            },
        };
        let alternate = allow_indirect
            .then(|| self.portal_path(emission, receiver))
            .flatten();
        Ok(alternate
            .filter(|path| path_score(*path) > path_score(direct))
            .unwrap_or(direct))
    }

    fn portal_path(
        &self,
        emission: &SoundEmission,
        receiver: AcousticReceiver,
    ) -> Option<ResolvedPath> {
        let start_zone = self.resolve_zone(emission.zone, emission.position)?;
        let end_zone = self.resolve_zone(receiver.zone, receiver.position)?;
        if start_zone == end_zone {
            return None;
        }
        self.portal_routes
            .get(&(start_zone, end_zone))?
            .iter()
            .map(|route| {
                let gain = route.portal_indices.iter().fold(route.gain, |gain, index| {
                    let portal = &self.topology.portals()[*index];
                    let open = self.portal_open(portal.id, portal.default_open_q16);
                    gain.multiplied(BandEnergy([open.max(256); 3]))
                });
                ResolvedPath {
                    length_mm: emission
                        .position
                        .distance(route.first_portal)
                        .saturating_add(route.length_mm)
                        .saturating_add(route.last_portal.distance(receiver.position)),
                    gain,
                    direction_target: route.first_portal,
                    direct: false,
                    uncertainty_q16: 16_384,
                }
            })
            .max_by_key(|path| path_score(*path))
    }

    fn portal_open(&self, portal_id: u32, default: u16) -> u16 {
        let portal = self
            .topology
            .portals()
            .iter()
            .find(|portal| portal.id == portal_id);
        portal
            .and_then(|portal| portal.instance_id)
            .and_then(|instance| self.active_states.get(&instance))
            .and_then(|state| state.portal_open_q16)
            .unwrap_or(default)
    }

    fn resolve_zone(&self, hint: Option<u32>, position: PositionMm) -> Option<u32> {
        resolve_zone(&self.topology, hint, position)
    }

    fn zones_may_connect(&self, source: Option<u32>, receiver: Option<u32>) -> bool {
        source.is_none()
            || receiver.is_none()
            || source == receiver
            || source
                .zip(receiver)
                .is_some_and(|pair| self.portal_routes.contains_key(&pair))
    }

    fn retain_recent(&mut self, current_sample: u64) {
        let keep_after = current_sample.saturating_sub(48 * SAMPLES_PER_TICK);
        self.recent_observations
            .retain(|observation| observation.arrival_sample >= keep_after);
        for observation in &self.frame.observations {
            if self.recent_observations.len() >= self.settings.max_recent_observations {
                let _oldest = self.recent_observations.remove(0);
            }
            self.recent_observations.push(*observation);
        }
        self.recent_observations.sort_by_key(|observation| {
            (
                observation.arrival_sample,
                observation.receiver_id,
                observation.observation_token,
            )
        });
    }

    fn publish_staged_structure(&mut self) -> Result<(), Error> {
        if self.staged_states.is_empty() {
            return Ok(());
        }
        for (id, state) in core::mem::take(&mut self.staged_states) {
            self.active_states.insert(id, state);
        }
        self.active_geometry = build_active_geometry(
            &self.spatial_device,
            &self.scene,
            &self.topology,
            &self.prefabs,
            &self.active_states,
        )?;
        self.version = AcousticStructureVersion(self.version.0.saturating_add(1));
        Ok(())
    }
}

fn resolve_zone(
    topology: &AcousticTopology,
    hint: Option<u32>,
    position: PositionMm,
) -> Option<u32> {
    if let Some(zone) = hint.filter(|zone| topology.zones().iter().any(|value| value.id == *zone)) {
        return Some(zone);
    }
    topology
        .zones()
        .iter()
        .find(|zone| zone.bounds.contains(position))
        .map(|zone| zone.id)
}

#[derive(Debug, Clone)]
struct RouteSearch {
    zone: u32,
    visited: Vec<u32>,
    portal_indices: Vec<usize>,
    length_mm: u64,
    gain: BandEnergy,
    first_portal: Option<PositionMm>,
    last_portal: Option<PositionMm>,
}

#[derive(Debug, Clone)]
struct CachedPortalRoute {
    portal_indices: Vec<usize>,
    length_mm: u64,
    gain: BandEnergy,
    first_portal: PositionMm,
    last_portal: PositionMm,
}

fn validate_settings(settings: AcousticWorldSettings) -> Result<(), Error> {
    if settings.max_receivers == 0
        || settings.max_active_emissions == 0
        || settings.max_candidate_pairs == 0
        || settings.max_paths_per_pair == 0
        || settings.max_transmission_surfaces == 0
        || settings.max_client_voices == 0
        || settings.max_recent_observations == 0
    {
        return Err(Error::InvalidField("acoustic world settings"));
    }
    Ok(())
}

fn validate_material_indices(
    triangles: &[QuantizedTriangle],
    material_count: usize,
) -> Result<(), Error> {
    if triangles
        .iter()
        .any(|triangle| usize::from(triangle.material_index) >= material_count)
    {
        Err(Error::MissingReference(
            "acoustic material index".to_owned(),
        ))
    } else {
        Ok(())
    }
}

fn build_active_geometry(
    device: &SpatialQueryDevice,
    scene: &AcousticSimulationScene,
    topology: &AcousticTopology,
    prefabs: &BTreeMap<String, AcousticPrefab>,
    states: &BTreeMap<u32, AcousticDynamicState>,
) -> Result<ActiveGeometry, Error> {
    let mut triangles = scene.triangles.clone();
    for instance in topology.instances() {
        let Some(dynamic) = states.get(&instance.id) else {
            continue;
        };
        let Some(state_id) = dynamic.state_id else {
            continue;
        };
        let state = prefabs
            .get(&instance.prefab)
            .and_then(|prefab| prefab.state(state_id))
            .ok_or_else(|| {
                Error::MissingReference(format!("{} state {state_id}", instance.prefab))
            })?;
        triangles.extend(
            state
                .triangles
                .iter()
                .copied()
                .map(|triangle| triangle.transformed(dynamic.transform)),
        );
    }
    let material_indices = triangles
        .iter()
        .map(|triangle| triangle.material_index)
        .collect::<Vec<_>>();
    let mut builder = device.create_scene()?;
    let geometry_id = if triangles.is_empty() {
        None
    } else {
        let spatial_triangles = triangles
            .iter()
            .map(|triangle| {
                SpatialQueryTriangle::new(triangle.vertices.map(spatial_position))
                    .map_err(Error::from)
            })
            .collect::<Result<Vec<_>, _>>()?;
        Some(builder.add_triangles(&spatial_triangles)?)
    };
    Ok(ActiveGeometry {
        scene: builder.commit()?,
        geometry_id,
        material_indices,
    })
}

#[allow(
    clippy::cast_precision_loss,
    reason = "authoritative millimetre coordinates are converted at the Embree f32 boundary"
)]
fn spatial_position(position: PositionMm) -> Vec3A {
    Vec3A::new(position.x as f32, position.y as f32, position.z as f32)
}

#[allow(
    clippy::too_many_lines,
    reason = "stable bounded route enumeration keeps ordering and tie-break rules visible together"
)]
fn build_portal_routes(
    topology: &AcousticTopology,
    scene: &AcousticSimulationScene,
    max_paths: usize,
) -> Result<BTreeMap<(u32, u32), Vec<CachedPortalRoute>>, Error> {
    let mut cache = BTreeMap::new();
    let mut expansions = 0_usize;
    for start in topology.zones() {
        for end in topology.zones() {
            if start.id == end.id {
                continue;
            }
            let mut pending = vec![RouteSearch {
                zone: start.id,
                visited: vec![start.id],
                portal_indices: Vec::new(),
                length_mm: 0,
                gain: BandEnergy::UNITY,
                first_portal: None,
                last_portal: None,
            }];
            let mut completed = Vec::new();
            while let Some(route) = pending.pop() {
                for (portal_index, portal) in topology.portals().iter().enumerate() {
                    expansions = expansions
                        .checked_add(1)
                        .ok_or(Error::ResourceLimit("portal route expansions"))?;
                    if expansions > MAX_PORTAL_ROUTE_EXPANSIONS {
                        return Err(Error::ResourceLimit("portal route expansions"));
                    }
                    let next = if portal.zone_a == route.zone {
                        Some(portal.zone_b)
                    } else if portal.zone_b == route.zone {
                        Some(portal.zone_a)
                    } else {
                        None
                    };
                    let Some(next) = next else { continue };
                    if route.visited.contains(&next) {
                        continue;
                    }
                    let mut candidate = route.clone();
                    candidate.zone = next;
                    candidate.visited.push(next);
                    candidate.portal_indices.push(portal_index);
                    candidate.length_mm = candidate.length_mm.saturating_add(zone_edge_length(
                        scene,
                        route.zone,
                        next,
                        portal.center,
                    ));
                    candidate.gain = candidate
                        .gain
                        .multiplied(zone_edge_gain(scene, route.zone, next));
                    candidate.first_portal.get_or_insert(portal.center);
                    candidate.last_portal = Some(portal.center);
                    if next == end.id {
                        completed.push(candidate);
                    } else if candidate.visited.len() <= topology.zones().len() {
                        pending.push(candidate);
                    }
                }
                pending.sort_by(|left, right| {
                    right
                        .length_mm
                        .cmp(&left.length_mm)
                        .then_with(|| right.visited.cmp(&left.visited))
                });
                if completed.len() >= max_paths {
                    completed.sort_by(compare_routes);
                    completed.truncate(max_paths);
                    let cutoff = completed
                        .last()
                        .map_or(u64::MAX, |candidate| candidate.length_mm);
                    if pending
                        .last()
                        .is_none_or(|candidate| candidate.length_mm > cutoff)
                    {
                        break;
                    }
                }
            }
            completed.sort_by(compare_routes);
            completed.truncate(max_paths);
            let routes = completed
                .into_iter()
                .filter_map(|route| {
                    Some(CachedPortalRoute {
                        portal_indices: route.portal_indices,
                        length_mm: route.length_mm,
                        gain: route.gain,
                        first_portal: route.first_portal?,
                        last_portal: route.last_portal?,
                    })
                })
                .collect::<Vec<_>>();
            if !routes.is_empty() {
                cache.insert((start.id, end.id), routes);
            }
        }
    }
    Ok(cache)
}

fn compare_routes(left: &RouteSearch, right: &RouteSearch) -> std::cmp::Ordering {
    left.length_mm
        .cmp(&right.length_mm)
        .then_with(|| right.gain.peak().cmp(&left.gain.peak()))
        .then_with(|| left.portal_indices.cmp(&right.portal_indices))
}

fn zone_edge_length(
    scene: &AcousticSimulationScene,
    left: u32,
    right: u32,
    fallback: PositionMm,
) -> u64 {
    scene
        .paths
        .iter()
        .filter(|edge| {
            (edge.zone_a == left && edge.zone_b == right)
                || (edge.zone_a == right && edge.zone_b == left)
        })
        .map(|edge| edge.length_mm)
        .min()
        .unwrap_or_else(|| fallback.distance(PositionMm::default()).max(1_000))
}

fn zone_edge_gain(scene: &AcousticSimulationScene, left: u32, right: u32) -> BandEnergy {
    scene
        .paths
        .iter()
        .filter(|edge| {
            (edge.zone_a == left && edge.zone_b == right)
                || (edge.zone_a == right && edge.zone_b == left)
        })
        .max_by_key(|edge| edge.gain.peak())
        .map_or(BandEnergy::UNITY, |edge| edge.gain)
}

fn path_score(path: ResolvedPath) -> (u16, Reverse<u64>, bool) {
    (path.gain.peak(), Reverse(path.length_mm), path.direct)
}

fn descriptor(
    version: AcousticStructureVersion,
    scene: &AcousticSimulationScene,
    emission: &SoundEmission,
    receiver: AcousticReceiver,
    path: ResolvedPath,
) -> PropagationDescriptor {
    let distance_loss = distance_loss_db_q8(path.length_mm);
    let directivity = directivity_gain(emission, receiver.position);
    let path_gain = if path.direct {
        path.gain
    } else {
        path.gain.multiplied(zone_late_gain(scene, receiver.zone))
    };
    let effective_gain = path_gain.multiplied(BandEnergy([directivity; 3]));
    let material_loss = gain_loss_db_q8(effective_gain.peak());
    PropagationDescriptor {
        structure_version: version,
        arrival_sample: emission
            .start_sample
            .saturating_add(arrival_delay_samples(path.length_mm)),
        path_length_mm: path.length_mm,
        gain_db_q8: distance_loss.saturating_add(material_loss),
        band_gain: effective_gain,
        direction_q15: direction(receiver.position, path.direction_target),
        uncertainty_q16: path.uncertainty_q16,
        direct: path.direct,
    }
}

fn zone_late_gain(scene: &AcousticSimulationScene, zone: Option<u32>) -> BandEnergy {
    zone.and_then(|zone| scene.zones.iter().find(|response| response.zone == zone))
        .map_or(BandEnergy::UNITY, |response| response.late_gain)
}

fn directivity_gain(emission: &SoundEmission, receiver: PositionMm) -> u16 {
    if emission.directivity_q16 == 0 {
        return u16::MAX;
    }
    let toward = direction(emission.position, receiver);
    let dot = emission
        .forward_q15
        .iter()
        .zip(toward)
        .map(|(left, right)| i64::from(*left) * i64::from(right))
        .sum::<i64>()
        .max(0);
    let facing_q16 = u32::try_from(dot / i64::from(i16::MAX))
        .unwrap_or(0)
        .min(u32::from(u16::MAX));
    let loss = u32::from(emission.directivity_q16)
        .saturating_mul(u32::from(u16::MAX).saturating_sub(facing_q16))
        / u32::from(u16::MAX);
    u16::try_from(u32::from(u16::MAX).saturating_sub(loss)).unwrap_or(0)
}

/// Convert path length to speed-of-sound delay with canonical integer rounding.
#[must_use]
pub fn arrival_delay_samples(length_mm: u64) -> u64 {
    length_mm
        .saturating_mul(ACOUSTIC_SAMPLE_RATE)
        .saturating_add(SOUND_SPEED_MM_PER_SECOND / 2)
        / SOUND_SPEED_MM_PER_SECOND
}

#[allow(
    clippy::cast_possible_truncation,
    clippy::cast_precision_loss,
    reason = "quantized path length is converted to a bounded Q8.8 attenuation value"
)]
fn distance_loss_db_q8(length_mm: u64) -> i32 {
    let metres = (length_mm.max(1_000) as f64) / 1_000.0;
    let value = (-20.0 * metres.log10() * 256.0).round();
    value.clamp(f64::from(i32::MIN), 0.0) as i32
}

#[allow(
    clippy::cast_possible_truncation,
    reason = "Q0.16 material gain is converted to a bounded Q8.8 attenuation value"
)]
fn gain_loss_db_q8(gain: u16) -> i32 {
    if gain == 0 {
        return i32::MIN;
    }
    let normalized = f64::from(gain) / f64::from(u16::MAX);
    let value = (20.0 * normalized.log10() * 256.0).round();
    value.clamp(f64::from(i32::MIN), 0.0) as i32
}

fn direction(origin: PositionMm, target: PositionMm) -> [i16; 3] {
    let length = origin.distance(target).max(1);
    let component = |value: i64| {
        let scaled = i128::from(value) * i128::from(i16::MAX);
        let divided = scaled / i128::from(length);
        i16::try_from(divided).unwrap_or(if divided < 0 { i16::MIN } else { i16::MAX })
    };
    [
        component(i64::from(target.x) - i64::from(origin.x)),
        component(i64::from(target.y) - i64::from(origin.y)),
        component(i64::from(target.z) - i64::from(origin.z)),
    ]
}

fn observation_token(receiver: u32, emission: u64, arrival: u64) -> u64 {
    let mut hasher = blake3::Hasher::new();
    hasher.update(b"blackflower.acoustic-observation.v1");
    hasher.update(&receiver.to_le_bytes());
    hasher.update(&emission.to_le_bytes());
    hasher.update(&arrival.to_le_bytes());
    let bytes: [u8; 8] = hasher.finalize().as_bytes()[..8]
        .try_into()
        .unwrap_or([0; 8]);
    u64::from_le_bytes(bytes)
}

fn canonicalize_frame(frame: &mut AcousticFrame) {
    frame.observations.sort_by_key(|observation| {
        (
            observation.arrival_sample,
            Reverse(observation.energy.peak()),
            observation.receiver_id,
            observation.observation_token,
        )
    });
    frame.sounds.sort_by_key(|delivery| {
        (
            delivery.play_sample,
            delivery.receiver_id,
            delivery.client_event_id,
        )
    });
    frame.voices.sort_by_key(|delivery| {
        (
            delivery.play_sample,
            delivery.receiver_id,
            delivery.encoded.stream,
            delivery.encoded.sequence,
        )
    });
}

#[cfg(test)]
#[path = "../tests/unit/solver.rs"]
mod tests;
