[package]
name = "blackflower-agent"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = []
profile-with-tracy = ["blackflower-observability/profile-with-tracy"]

[dependencies]
blackflower-harness = { workspace = true, features = ["observability"] }
blackflower-navigation.workspace = true
blackflower-networking.workspace = true
blackflower-networking-quic.workspace = true
blackflower-observability.workspace = true
blackflower-observability-tui.workspace = true
blackflower-process.workspace = true

anyhow.workspace = true
clap.workspace = true
metrics.workspace = true
ratatui.workspace = true
strum.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true

[lints]
workspace = true
