include_guard(GLOBAL)

set(VCPKG_TARGET_ARCHITECTURE x64)
include("$ENV{VCPKG_ROOT}/scripts/toolchains/linux.cmake")

set(CMAKE_C_COMPILER clang-21)
set(CMAKE_CXX_COMPILER clang++-21)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_CXX_SCAN_FOR_MODULES OFF)

find_program(SCCACHE_EXECUTABLE NAMES sccache REQUIRED)
set(CMAKE_C_COMPILER_LAUNCHER "${SCCACHE_EXECUTABLE}")
set(CMAKE_CXX_COMPILER_LAUNCHER "${SCCACHE_EXECUTABLE}")
