[package]
name = "blackflower-networking"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
blackflower-acoustics.workspace = true
thiserror.workspace = true

[dev-dependencies]
blackflower-audio-capture.workspace = true
blackflower-audio-voice.workspace = true

[lints]
workspace = true
