#include <DetourAlloc.h>
#include <DetourNavMeshBuilder.h>

#include <cstdio>

int main() {
    constexpr unsigned short border = 0x800f;
    const unsigned short vertices[] = {
        0, 0, 0,
        0, 0, 10,
        10, 0, 10,
        10, 0, 0,
    };
    const unsigned short polygons[] = {
        0, 1, 2, 3,
        border, border, border, border,
    };
    const unsigned short polygon_flags[] = {1};
    const unsigned char polygon_areas[] = {0};

    dtNavMeshCreateParams params {};
    params.verts = vertices;
    params.vertCount = 4;
    params.polys = polygons;
    params.polyFlags = polygon_flags;
    params.polyAreas = polygon_areas;
    params.polyCount = 1;
    params.nvp = 4;
    params.bmin[0] = 0.0F;
    params.bmin[1] = 0.0F;
    params.bmin[2] = 0.0F;
    params.bmax[0] = 10.0F;
    params.bmax[1] = 1.0F;
    params.bmax[2] = 10.0F;
    params.walkableHeight = 2.0F;
    params.walkableRadius = 0.5F;
    params.walkableClimb = 0.5F;
    params.cs = 1.0F;
    params.ch = 1.0F;
    params.buildBvTree = true;

    unsigned char *data = nullptr;
    int data_size = 0;
    if (!dtCreateNavMeshData(&params, &data, &data_size)) {
        return 1;
    }

    std::puts("// Generated by tests/fixtures/generate_quad.cpp.");
    std::puts("pub const QUAD_NAVMESH_TILE: &[u8] = &[");
    for (int index = 0; index < data_size; ++index) {
        std::printf("%u,", static_cast<unsigned int>(data[index]));
        if ((index + 1) % 16 == 0) {
            std::putchar('\n');
        }
    }
    std::puts("\n];");
    dtFree(data);
    return 0;
}
