[package]
name = "blackflower-audio-voice"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true
links = "opus"

[dependencies]
thiserror.workspace = true

[build-dependencies]
bindgen.workspace = true
cmake.workspace = true

[lints]
workspace = true
